### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [brianavise88/prj-rev-bwfs-dasmoto#5]
**Grade:** Meets Expectations

**Summary:** This project is good! It meets the spec and your code is clean and error free. One area of improvement is reviewing your CSS for any repeated styles and trying to reduce them, will make your CSS cleaner and more maintainable. Also, focus on consistent indentation in your code to make your code cleaner and more readable!

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline- block.html.

I’d also suggest checking out HTML codes, which will help explain my comment on the & usage in your HTML!

Good luck!

**Comment by brianavise88** [comment]
I will fix everything you suggested and reload the file tomorrow. I really appreciate the feed back.
